let items = [];

const lines = [
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
  `Lorem ipsum dolor sit, amet consectetur adipisicing elit.`,
];

let i = 0;

items = lines.map((n) => `<p id="line${i++}">` + n + `</p>`);

const html = items.join('');

document.getElementById('container').innerHTML = html;

const breathFrames = [
  { fontVariationSettings: `"wght" 100, "wdth" 75, "slnt" 0` },
  { fontVariationSettings: `"wght" 900, "wdth" 125, "slnt" -12` },
];

const breathTiming = {
  id: 'breath',
  delay: 100,
  direction: 'normal',
  duration: 1000,
  fill: 'none',
  easing: 'cubic-bezier(0.45, 0, 0.55, 1)',
  iterationStart: 0.0,
  iterations: '3',
  composite: 'replace',
  iterationComposite: 'replace',
};

document.getElementById('line0').animate(breathFrames, breathTiming);

const elements = document.getElementsByTagName('p');

for (let element of elements) {
  element.animate(breathFrames, breathTiming);
}

let observer = new IntersectionObserver(function (entries, observer) {
  entries.forEach(function (entry) {
    // Pause/Play the animation
    if (entry.isIntersecting) entry.target.style.animationPlayState = 'running';
    else entry.target.style.animationPlayState = 'paused';
  });
});

// document.getElementsByTagName.forEach(function (elements) {
//   observer.observe(elements);
// });

for (let element of elements) {
  observer.observe(element);
}
